### ISSUE TITLE
Ubuntu16.04 LTS中安装wireshark | Line's Blog

### ISSUE THREAD

**Issue by fanzhenyu95** [fzy-Line/fzy-Line.github.io#112]
http://fanzhenyu.me/2017/12/02/Ubuntu16-04-LTS%E4%B8%AD%E5%AE%89%E8%A3%85wireshark/

**Comment by Chao-ou** [comment]
其实有个小后门，直接打开软件中心搜索wireshark一键安装

**Comment by fanzhenyu95** [comment]
哈哈，之前一直习惯用命令行安装软件，刚刚试了下确实可以在软件中心安装。
